name: classroom
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  intl: ^0.18.1
  shared_preferences: ^2.0.8
  http: ^1.1.0
  provider: ^6.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Black.ttf
        - asset: assets/fonts/ProximaNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova-Light.ttf
          weight: 500
        - asset: assets/fonts/ProximaNova-Semibold.ttf
          weight: 600
        - asset: assets/fonts/ProximaNova-Light.ttf
          weight: 300
